import type {
  Agent,
  Assistant,
  AssistantOrchestration,
  AssistantRelease,
  BusinessDomain,
  CatalogSummary,
  ResourceBlueprint,
  Resource,
  ResourceCenter,
  ResourceVersion,
  Scenario,
  TaskInstance,
  UserSession,
  WorkflowInstance,
} from '../types';

const now = () => new Date().toISOString();

const session: UserSession = {
  userId: 'u-demo-domain-admin',
  displayName: 'Lynxus Demo User',
  currentRole: 'DOMAIN_ADMIN',
  availableRoles: ['PLATFORM_ADMIN', 'DOMAIN_ADMIN', 'DEVELOPER', 'BUSINESS_USER'],
};

const kbVersion: ResourceVersion = {
  id: 'resource-version-kb-v1',
  resourceId: 'resource-kb-support',
  version: '1.0.0',
  status: 'PUBLISHED',
  summary: '客服 FAQ 稳定版',
  configDigest: 'digest-kb-v1',
  createdAt: now(),
  publishedAt: now(),
  configuration: {
    type: 'KNOWLEDGE_BASE',
    knowledgeBase: {
      sourceType: 'OBJECT_STORAGE',
      sourceLocation: 'seed://support-faq',
      syncMode: 'MANUAL',
      retrievalMode: 'HYBRID',
      embeddingModel: 'text-embedding-3-large',
      chunkStrategy: 'markdown-512-overlap-80',
      defaultTopK: 5,
      documentCount: 12,
    },
  },
};

const refundSkillVersion: ResourceVersion = {
  id: 'resource-version-refund-v1',
  resourceId: 'resource-skill-refund',
  version: '1.0.0',
  status: 'PUBLISHED',
  summary: '退款策略执行器',
  configDigest: 'digest-refund-v1',
  createdAt: now(),
  publishedAt: now(),
  configuration: {
    type: 'SKILL',
    skill: {
      runtime: 'HTTP',
      endpoint: 'http://demo.local/skills/refund-policy',
      method: 'POST',
      authType: 'NONE',
      timeoutSeconds: 10,
      retryPolicy: 'FIXED_2_RETRIES',
      inputSchema: '{question, customer_profile}',
      outputSchema: '{decision, reason, route_key}',
    },
  },
};

const ticketMcpVersion: ResourceVersion = {
  id: 'resource-version-ticket-v1',
  resourceId: 'resource-mcp-ticket',
  version: '1.0.0',
  status: 'PUBLISHED',
  summary: '工单协同 MCP',
  configDigest: 'digest-ticket-v1',
  createdAt: now(),
  publishedAt: now(),
  configuration: {
    type: 'MCP',
    mcp: {
      serverName: 'ticketing-server',
      transport: 'STREAMABLE_HTTP',
      connectionUri: 'http://demo.local/mcp/ticketing',
      namespace: 'support.ticket',
      authType: 'NONE',
      heartbeatSeconds: 30,
      exposedTools: ['create_ticket', 'append_comment'],
    },
  },
};

const llmVersion: ResourceVersion = {
  id: 'resource-version-llm-v1',
  resourceId: 'resource-llm-openai',
  version: '1.0.0',
  status: 'PUBLISHED',
  summary: '主模型',
  configDigest: 'digest-llm-v1',
  createdAt: now(),
  publishedAt: now(),
  configuration: {
    type: 'LLM_MODEL',
      llmModel: {
        providerType: 'OPENAI_COMPATIBLE',
        modelId: 'demo-support-model',
        baseUrl: 'http://localhost:11434/v1',
        apiKeyEnvVar: 'OPENAI_COMPATIBLE_API_KEY',
        organization: 'lynxus-demo',
        project: 'customer-ops',
      region: 'local',
      temperature: 0.2,
      maxTokens: 1200,
    },
  },
};

const promptVersion: ResourceVersion = {
  id: 'resource-version-prompt-v1',
  resourceId: 'resource-prompt-support',
  version: '1.0.0',
  status: 'PUBLISHED',
  summary: '客服默认 Prompt',
  configDigest: 'digest-prompt-v1',
  createdAt: now(),
  publishedAt: now(),
  configuration: {
    type: 'PROMPT_TEMPLATE',
    promptTemplate: {
      templateType: 'CHAT',
      systemPrompt: '你是企业智能客服编排中的一个专业智能体。',
      userPromptTemplate: '用户问题：{{question}}\n上下文：{{knowledge_context}}',
      responseFormat: 'markdown',
    },
  },
};

const resources: Resource[] = [
  {
    id: 'resource-kb-support',
    domainId: 'domain-support',
    name: '客服知识库',
    type: 'KNOWLEDGE_BASE',
    shareScope: 'DOMAIN_SHARED',
    ownerType: 'DOMAIN',
    ownerId: 'domain-support',
    summary: '常见问题与操作步骤知识库',
    steward: '客服知识运营',
    tags: ['FAQ', 'RAG'],
    latestVersion: kbVersion,
    effectiveVersion: kbVersion,
    versions: [kbVersion],
  },
  {
    id: 'resource-skill-refund',
    domainId: 'domain-support',
    name: '退款策略 Skill',
    type: 'SKILL',
    shareScope: 'PRIVATE',
    ownerType: 'ASSISTANT',
    ownerId: 'assistant-customer-ops',
    summary: '用于售后判断退款和补偿策略',
    steward: '售后策略团队',
    tags: ['售后', '退款'],
    latestVersion: refundSkillVersion,
    effectiveVersion: refundSkillVersion,
    versions: [refundSkillVersion],
  },
  {
    id: 'resource-mcp-ticket',
    domainId: 'domain-support',
    name: '工单协同 MCP',
    type: 'MCP',
    shareScope: 'DOMAIN_SHARED',
    ownerType: 'DOMAIN',
    ownerId: 'domain-support',
    summary: '人工协同工单系统连接器',
    steward: '客服平台集成',
    tags: ['MCP', '工单'],
    latestVersion: ticketMcpVersion,
    effectiveVersion: ticketMcpVersion,
    versions: [ticketMcpVersion],
  },
  {
    id: 'resource-llm-openai',
    domainId: 'domain-support',
    name: '客服主模型',
    type: 'LLM_MODEL',
    shareScope: 'DOMAIN_SHARED',
    ownerType: 'DOMAIN',
    ownerId: 'domain-support',
    summary: '用于路由、问答和总结的默认模型',
    steward: '平台 AI 工程团队',
    tags: ['LLM'],
    latestVersion: llmVersion,
    effectiveVersion: llmVersion,
    versions: [llmVersion],
  },
  {
    id: 'resource-prompt-support',
    domainId: 'domain-support',
    name: '客服 Prompt 模板',
    type: 'PROMPT_TEMPLATE',
    shareScope: 'PRIVATE',
    ownerType: 'ASSISTANT',
    ownerId: 'assistant-customer-ops',
    summary: '客服助手默认系统提示模板',
    steward: '客服编排团队',
    tags: ['Prompt'],
    latestVersion: promptVersion,
    effectiveVersion: promptVersion,
    versions: [promptVersion],
  },
];

const agents: Agent[] = [
  {
    id: 'agent-router',
    assistantId: 'assistant-customer-ops',
    name: '问题路由智能体',
    role: 'router',
    instructions: '识别用户问题属于 FAQ、售后还是需要人工接管的投诉。',
    bindings: [
      {
        id: 'binding-router-kb',
        resourceId: 'resource-kb-support',
        resourceVersionId: 'resource-version-kb-v1',
        resourceVersion: '1.0.0',
        consumerType: 'AGENT',
        consumerId: 'agent-router',
        createdAt: now(),
      },
    ],
    executionPolicy: {
      inheritAssistantDefaults: true,
      modelResourceId: null,
      promptTemplateResourceId: null,
      inlinePrompt: '输出结构化路由决策。',
      ragEnabled: true,
      knowledgeBaseResourceId: 'resource-kb-support',
      memoryWindowSize: 8,
      toolResourceIds: [],
    },
  },
  {
    id: 'agent-faq',
    assistantId: 'assistant-customer-ops',
    name: 'FAQ 智能体',
    role: 'faq',
    instructions: '根据知识库回答标准问题。',
    bindings: [],
    executionPolicy: {
      inheritAssistantDefaults: true,
      modelResourceId: null,
      promptTemplateResourceId: null,
      inlinePrompt: '优先根据知识库输出清晰、可执行答案。',
      ragEnabled: true,
      knowledgeBaseResourceId: 'resource-kb-support',
      memoryWindowSize: 8,
      toolResourceIds: [],
    },
  },
  {
    id: 'agent-policy',
    assistantId: 'assistant-customer-ops',
    name: '售后策略智能体',
    role: 'policy',
    instructions: '调用售后策略 Skill 评估退款或补偿方案。',
    bindings: [
      {
        id: 'binding-policy-skill',
        resourceId: 'resource-skill-refund',
        resourceVersionId: 'resource-version-refund-v1',
        resourceVersion: '1.0.0',
        consumerType: 'AGENT',
        consumerId: 'agent-policy',
        createdAt: now(),
      },
    ],
    executionPolicy: {
      inheritAssistantDefaults: true,
      modelResourceId: null,
      promptTemplateResourceId: null,
      inlinePrompt: '结合 Skill 结果给出售后处置建议。',
      ragEnabled: true,
      knowledgeBaseResourceId: 'resource-kb-support',
      memoryWindowSize: 8,
      toolResourceIds: ['resource-skill-refund'],
    },
  },
  {
    id: 'agent-coordinator',
    assistantId: 'assistant-customer-ops',
    name: '人工协同智能体',
    role: 'handoff',
    instructions: '在人工节点前后同步工单和总结。',
    bindings: [
      {
        id: 'binding-coordinator-mcp',
        resourceId: 'resource-mcp-ticket',
        resourceVersionId: 'resource-version-ticket-v1',
        resourceVersion: '1.0.0',
        consumerType: 'AGENT',
        consumerId: 'agent-coordinator',
        createdAt: now(),
      },
    ],
    executionPolicy: {
      inheritAssistantDefaults: true,
      modelResourceId: null,
      promptTemplateResourceId: null,
      inlinePrompt: '总结上下文并同步人工协同结果。',
      ragEnabled: false,
      knowledgeBaseResourceId: null,
      memoryWindowSize: 12,
      toolResourceIds: ['resource-mcp-ticket'],
    },
  },
];

const orchestration: AssistantOrchestration = {
  assistantId: 'assistant-customer-ops',
  assistantName: '客户协同助手',
  scenarioId: 'scenario-customer-ops',
  executionMode: 'GRAPH',
  nodes: [
    { nodeKey: 'start', nodeName: '开始', nodeType: 'START', description: '用户消息进入编排', agentId: null, humanNode: null },
    { nodeKey: 'route', nodeName: '问题路由', nodeType: 'AGENT', description: '判断 FAQ、售后或人工协同', agentId: 'agent-router', humanNode: null },
    { nodeKey: 'faq', nodeName: 'FAQ 回答', nodeType: 'AGENT', description: '处理标准常见问题', agentId: 'agent-faq', humanNode: null },
    { nodeKey: 'policy', nodeName: '售后策略', nodeType: 'AGENT', description: '处理退款、补偿等售后问题', agentId: 'agent-policy', humanNode: null },
    {
      nodeKey: 'human-review',
      nodeName: '人工复核',
      nodeType: 'HUMAN',
      description: '复杂投诉转人工处理',
      agentId: null,
      humanNode: {
        title: '人工协同待办',
        instruction: '请确认投诉事实、处理方案与回复口径。',
        expectedAction: 'CONFIRM',
        resumeRouteKey: 'confirmed',
      },
    },
    { nodeKey: 'handoff-close', nodeName: '协同收口', nodeType: 'AGENT', description: '同步工单并形成最终结论', agentId: 'agent-coordinator', humanNode: null },
    { nodeKey: 'end', nodeName: '结束', nodeType: 'END', description: '流程完成', agentId: null, humanNode: null },
  ],
  edges: [
    { edgeKey: 'edge-start-route', sourceNodeKey: 'start', targetNodeKey: 'route', routeKey: null, label: '进入路由', defaultEdge: true },
    { edgeKey: 'edge-route-faq', sourceNodeKey: 'route', targetNodeKey: 'faq', routeKey: 'faq', label: 'FAQ', defaultEdge: false },
    { edgeKey: 'edge-route-policy', sourceNodeKey: 'route', targetNodeKey: 'policy', routeKey: 'after_sales', label: '售后', defaultEdge: false },
    { edgeKey: 'edge-route-human', sourceNodeKey: 'route', targetNodeKey: 'human-review', routeKey: 'human_handoff', label: '人工协同', defaultEdge: false },
    { edgeKey: 'edge-faq-end', sourceNodeKey: 'faq', targetNodeKey: 'end', routeKey: null, label: '回答完成', defaultEdge: true },
    { edgeKey: 'edge-policy-end', sourceNodeKey: 'policy', targetNodeKey: 'end', routeKey: 'resolved', label: '自动处理完成', defaultEdge: false },
    { edgeKey: 'edge-policy-human', sourceNodeKey: 'policy', targetNodeKey: 'human-review', routeKey: 'manual_review', label: '需要人工复核', defaultEdge: false },
    { edgeKey: 'edge-human-handoff', sourceNodeKey: 'human-review', targetNodeKey: 'handoff-close', routeKey: 'confirmed', label: '人工确认', defaultEdge: true },
    { edgeKey: 'edge-handoff-end', sourceNodeKey: 'handoff-close', targetNodeKey: 'end', routeKey: null, label: '收口完成', defaultEdge: true },
  ],
};

const release: AssistantRelease = {
  id: 'assistant-release-customer-ops-v1',
  assistantId: 'assistant-customer-ops',
  releaseVersion: '1.0.0',
  status: 'PUBLISHED',
  createdAt: now(),
  publishedAt: now(),
  resources: [
    {
      resourceId: 'resource-kb-support',
      resourceName: '客服知识库',
      resourceType: 'KNOWLEDGE_BASE',
      resourceVersionId: 'resource-version-kb-v1',
      resourceVersion: '1.0.0',
      boundAgents: ['问题路由智能体', 'FAQ 智能体', '售后策略智能体'],
      configuration: kbVersion.configuration,
    },
    {
      resourceId: 'resource-skill-refund',
      resourceName: '退款策略 Skill',
      resourceType: 'SKILL',
      resourceVersionId: 'resource-version-refund-v1',
      resourceVersion: '1.0.0',
      boundAgents: ['售后策略智能体'],
      configuration: refundSkillVersion.configuration,
    },
    {
      resourceId: 'resource-mcp-ticket',
      resourceName: '工单协同 MCP',
      resourceType: 'MCP',
      resourceVersionId: 'resource-version-ticket-v1',
      resourceVersion: '1.0.0',
      boundAgents: ['人工协同智能体'],
      configuration: ticketMcpVersion.configuration,
    },
    {
      resourceId: 'resource-llm-openai',
      resourceName: '客服主模型',
      resourceType: 'LLM_MODEL',
      resourceVersionId: 'resource-version-llm-v1',
      resourceVersion: '1.0.0',
      boundAgents: [],
      configuration: llmVersion.configuration,
    },
    {
      resourceId: 'resource-prompt-support',
      resourceName: '客服 Prompt 模板',
      resourceType: 'PROMPT_TEMPLATE',
      resourceVersionId: 'resource-version-prompt-v1',
      resourceVersion: '1.0.0',
      boundAgents: [],
      configuration: promptVersion.configuration,
    },
  ],
  agents: agents.map((agent) => ({
    agentId: agent.id,
    name: agent.name,
    role: agent.role,
    instructions: agent.instructions,
    executionPolicy: agent.executionPolicy,
    bindingResourceVersionIds: agent.bindings.map((binding) => binding.resourceVersionId),
  })),
  orchestration,
  modelPolicy: {
    providerResourceId: 'resource-llm-openai',
    promptTemplateResourceId: 'resource-prompt-support',
    temperature: 0.2,
    maxTokens: 1200,
  },
  ragPolicy: {
    enabled: true,
    knowledgeBaseResourceId: 'resource-kb-support',
    topK: 5,
  },
  memoryPolicy: {
    enabled: true,
    windowSize: 8,
  },
};

const assistant: Assistant = {
  id: 'assistant-customer-ops',
  scenarioId: 'scenario-customer-ops',
  name: '客户协同助手',
  description: '按图编排 FAQ、售后和人工协同的多智能体助手。',
  version: { version: '1.0.0', status: 'PUBLISHED', updatedAt: now() },
  agents,
  currentRelease: release,
  releases: [release],
  modelPolicy: release.modelPolicy,
  ragPolicy: release.ragPolicy,
  memoryPolicy: release.memoryPolicy,
};

const scenarios: Scenario[] = [
  {
    id: 'scenario-customer-ops',
    domainId: 'domain-support',
    name: '智能客服协同处理',
    goal: '在 FAQ、售后和人工接管之间进行真实图编排。',
    version: { version: '1.0.0', status: 'PUBLISHED', updatedAt: now() },
    assistants: [assistant],
  },
];

const domains: BusinessDomain[] = [
  {
    id: 'domain-support',
    name: '智能客服域',
    description: '客服问答、售后与人工协同编排域',
    scenarios,
    resources,
  },
];

const tasks: TaskInstance[] = [
  {
    id: 'task-faq-1',
    scenarioId: 'scenario-customer-ops',
    assistantId: 'assistant-customer-ops',
    assistantName: '客户协同助手',
    assistantReleaseVersion: '1.0.0',
    question: '怎么重置密码？',
    requester: '业务用户A',
    status: 'COMPLETED',
    createdAt: now(),
    workflowInstanceId: 'wf-faq-1',
  },
  {
    id: 'task-human-1',
    scenarioId: 'scenario-customer-ops',
    assistantId: 'assistant-customer-ops',
    assistantName: '客户协同助手',
    assistantReleaseVersion: '1.0.0',
    question: '客户投诉退款规则不合理，需要人工处理',
    requester: '业务用户B',
    status: 'WAITING_HUMAN',
    createdAt: now(),
    workflowInstanceId: 'wf-human-1',
  },
];

const workflows: WorkflowInstance[] = [
  {
    id: 'wf-faq-1',
    taskId: 'task-faq-1',
    assistantId: 'assistant-customer-ops',
    assistantName: '客户协同助手',
    assistantReleaseVersion: '1.0.0',
    status: 'COMPLETED',
    summary: 'FAQ 分支已自动完成。',
    finalReply: '可以通过登录页的“忘记密码”入口完成密码重置。',
    currentNodeKey: 'end',
    escalationRequired: false,
    checkpoint: null,
    humanTask: null,
    mcpSummary: null,
    resourceAnchors: ['客服知识库@1.0.0', '客服主模型@1.0.0', '客服 Prompt 模板@1.0.0'],
    nodes: [
      { id: 'wf-faq-node-1', workflowInstanceId: 'wf-faq-1', nodeKey: 'start', nodeName: '开始', status: 'COMPLETED', detail: '收到用户消息。', updatedAt: now() },
      { id: 'wf-faq-node-2', workflowInstanceId: 'wf-faq-1', nodeKey: 'route', nodeName: '问题路由', status: 'COMPLETED', detail: '路由到 FAQ 分支。', updatedAt: now() },
      { id: 'wf-faq-node-3', workflowInstanceId: 'wf-faq-1', nodeKey: 'faq', nodeName: 'FAQ 回答', status: 'COMPLETED', detail: '生成 FAQ 答复。', updatedAt: now() },
      { id: 'wf-faq-node-4', workflowInstanceId: 'wf-faq-1', nodeKey: 'end', nodeName: '结束', status: 'COMPLETED', detail: '流程完成。', updatedAt: now() },
    ],
    toolCalls: [],
    interventions: [],
  },
  {
    id: 'wf-human-1',
    taskId: 'task-human-1',
    assistantId: 'assistant-customer-ops',
    assistantName: '客户协同助手',
    assistantReleaseVersion: '1.0.0',
    status: 'WAITING_HUMAN',
    summary: '投诉问题已进入人工节点。',
    finalReply: null,
    currentNodeKey: 'human-review',
    escalationRequired: true,
    checkpoint: {
      checkpointId: 'cp-human-1',
      currentNodeKey: 'human-review',
      waitingNodeKey: 'human-review',
      statePayload: '{"customer":"业务用户B"}',
      resumeCount: 0,
    },
    humanTask: {
      nodeKey: 'human-review',
      title: '人工协同待办',
      instruction: '请确认投诉事实、补偿方案和回复口径。',
      expectedAction: 'CONFIRM',
    },
    mcpSummary: {
      capabilityName: '创建协同工单',
      externalTicketId: 'TICKET-10002',
      status: 'ACCEPTED',
      recommendedAction: 'HUMAN_HANDOFF',
      detail: '已创建人工协同工单，等待处理。',
    },
    resourceAnchors: ['客服知识库@1.0.0', '退款策略 Skill@1.0.0', '工单协同 MCP@1.0.0'],
    nodes: [
      { id: 'wf-human-node-1', workflowInstanceId: 'wf-human-1', nodeKey: 'start', nodeName: '开始', status: 'COMPLETED', detail: '收到用户消息。', updatedAt: now() },
      { id: 'wf-human-node-2', workflowInstanceId: 'wf-human-1', nodeKey: 'route', nodeName: '问题路由', status: 'COMPLETED', detail: '路由到人工协同分支。', updatedAt: now() },
      { id: 'wf-human-node-3', workflowInstanceId: 'wf-human-1', nodeKey: 'human-review', nodeName: '人工复核', status: 'WAITING_HUMAN', detail: '等待人工接管。', updatedAt: now() },
    ],
    toolCalls: [
      {
        id: 'tool-human-1',
        toolType: 'MCP',
        resourceId: 'resource-mcp-ticket',
        resourceName: '工单协同 MCP',
        operation: 'create_ticket',
        status: 'COMPLETED',
        detail: '创建工单 TICKET-10002',
        createdAt: now(),
      },
    ],
    interventions: [
      {
        id: 'human-intervention-1',
        workflowInstanceId: 'wf-human-1',
        action: 'WAIT_CONFIRM',
        operator: 'system',
        comment: '等待人工处理',
        createdAt: now(),
      },
    ],
  },
];

export const mockCatalogSummary: CatalogSummary = {
  domains,
  scenarios,
  assistants: [assistant],
  agents,
  resources,
  orchestrations: [orchestration],
  resourceCenter: {
    totalResources: resources.length,
    domainSharedResources: resources.filter((item) => item.shareScope === 'DOMAIN_SHARED').length,
    privateResources: resources.filter((item) => item.shareScope === 'PRIVATE').length,
    usages: [
      {
        resourceId: 'resource-kb-support',
        resourceName: '客服知识库',
        type: 'KNOWLEDGE_BASE',
        shareScope: 'DOMAIN_SHARED',
        ownerLabel: 'DOMAIN:domain-support',
        latestVersion: '1.0.0',
        effectiveVersion: '1.0.0',
        boundAgents: ['问题路由智能体', 'FAQ 智能体', '售后策略智能体'],
        boundAssistants: ['客户协同助手'],
        bindingAnchors: ['问题路由智能体 -> 1.0.0'],
      },
      {
        resourceId: 'resource-skill-refund',
        resourceName: '退款策略 Skill',
        type: 'SKILL',
        shareScope: 'PRIVATE',
        ownerLabel: 'ASSISTANT:assistant-customer-ops',
        latestVersion: '1.0.0',
        effectiveVersion: '1.0.0',
        boundAgents: ['售后策略智能体'],
        boundAssistants: ['客户协同助手'],
        bindingAnchors: ['售后策略智能体 -> 1.0.0'],
      },
      {
        resourceId: 'resource-mcp-ticket',
        resourceName: '工单协同 MCP',
        type: 'MCP',
        shareScope: 'DOMAIN_SHARED',
        ownerLabel: 'DOMAIN:domain-support',
        latestVersion: '1.0.0',
        effectiveVersion: '1.0.0',
        boundAgents: ['人工协同智能体'],
        boundAssistants: ['客户协同助手'],
        bindingAnchors: ['人工协同智能体 -> 1.0.0'],
      },
    ],
  } satisfies ResourceCenter,
  resourceBlueprints: [
    {
      type: 'KNOWLEDGE_BASE',
      label: '知识库',
      description: '管理文档来源、检索方式和默认召回策略。',
      maintainedFields: ['数据来源', '同步方式', '检索模式', 'Embedding', '切片策略'],
      defaultConfiguration: kbVersion.configuration,
    },
    {
      type: 'SKILL',
      label: 'Skill',
      description: '管理业务能力调用协议、超时和输入输出契约。',
      maintainedFields: ['端点', '方法', '鉴权', '超时', 'Schema'],
      defaultConfiguration: refundSkillVersion.configuration,
    },
    {
      type: 'MCP',
      label: 'MCP',
      description: '管理工具连接方式、命名空间和暴露工具。',
      maintainedFields: ['服务名', '连接地址', '命名空间', '工具列表'],
      defaultConfiguration: ticketMcpVersion.configuration,
    },
    {
      type: 'LLM_MODEL',
      label: 'LLM 模型',
      description: '管理模型供应商连接和默认参数。',
      maintainedFields: ['模型 ID', 'Base URL', 'API Key', 'Temperature', 'Max Tokens'],
      defaultConfiguration: llmVersion.configuration,
    },
    {
      type: 'PROMPT_TEMPLATE',
      label: 'Prompt 模板',
      description: '管理系统提示、用户模版与输出格式。',
      maintainedFields: ['System Prompt', 'User Template', '响应格式'],
      defaultConfiguration: promptVersion.configuration,
    },
  ] satisfies ResourceBlueprint[],
};

export const mockTasks = tasks;
export const mockWorkflows = workflows;
export const mockSession = session;
