import type {
  Agent,
  Assistant,
  AssistantOrchestration,
  BusinessDomain,
  CatalogSummary,
  ResourceBlueprint,
  Resource,
  ResourceCenter,
  ResourceVersion,
  ResourceVersionConfiguration,
  Scenario,
  TaskInstance,
  UserSession,
  WorkflowInstance,
} from '../types';

const session: UserSession = {
  userId: 'u-demo-domain-admin',
  displayName: 'Lynxus Demo User',
  currentRole: 'DOMAIN_ADMIN',
  availableRoles: ['PLATFORM_ADMIN', 'DOMAIN_ADMIN', 'DEVELOPER', 'BUSINESS_USER'],
};

const kbVersions: ResourceVersion[] = [
  {
    id: 'resource-version-kb-v1',
    resourceId: 'resource-kb-support',
    version: '1.0.0',
    status: 'PUBLISHED',
    summary: '客服 FAQ 稳定版',
    configDigest: 'digest-kb-v1',
    createdAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    configuration: {
      type: 'KNOWLEDGE_BASE',
      knowledgeBase: {
        sourceType: 'OBJECT_STORAGE',
        sourceLocation: 'minio://knowledge/support-faq',
        syncMode: 'SCHEDULED',
        retrievalMode: 'HYBRID',
        embeddingModel: 'text-embedding-3-large',
        chunkStrategy: 'markdown-512-overlap-80',
        defaultTopK: 5,
        documentCount: 1280,
      },
    },
  },
  {
    id: 'resource-version-kb-v1-1',
    resourceId: 'resource-kb-support',
    version: '1.1.0',
    status: 'DRAFT',
    summary: '补充密码重置与账号安全条目',
    configDigest: 'digest-kb-v1-1',
    createdAt: new Date().toISOString(),
    publishedAt: null,
    configuration: {
      type: 'KNOWLEDGE_BASE',
      knowledgeBase: {
        sourceType: 'OBJECT_STORAGE',
        sourceLocation: 'minio://knowledge/support-faq',
        syncMode: 'SCHEDULED',
        retrievalMode: 'HYBRID',
        embeddingModel: 'text-embedding-3-large',
        chunkStrategy: 'markdown-512-overlap-80',
        defaultTopK: 6,
        documentCount: 1460,
      },
    },
  },
];

const answerSkillVersions: ResourceVersion[] = [
  {
    id: 'resource-version-answer-v1',
    resourceId: 'resource-skill-answer',
    version: '1.0.0',
    status: 'PUBLISHED',
    summary: '答案生成稳定版',
    configDigest: 'digest-answer-v1',
    createdAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    configuration: {
      type: 'SKILL',
      skill: {
        runtime: 'HTTP',
        endpoint: 'https://skill-gateway.internal/answer',
        method: 'POST',
        authType: 'SERVICE_ACCOUNT',
        timeoutSeconds: 15,
        retryPolicy: 'EXPONENTIAL_BACKOFF',
        inputSchema: '{question, passages[]}',
        outputSchema: '{answer, confidence}',
      },
    },
  },
];

const refundSkillVersions: ResourceVersion[] = [
  {
    id: 'resource-version-refund-v1',
    resourceId: 'resource-skill-refund',
    version: '1.0.0',
    status: 'PUBLISHED',
    summary: '退款策略基线版',
    configDigest: 'digest-refund-v1',
    createdAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    configuration: {
      type: 'SKILL',
      skill: {
        runtime: 'WORKFLOW_ACTIVITY',
        endpoint: 'activity://refund-policy',
        method: 'RPC',
        authType: 'SERVICE_ACCOUNT',
        timeoutSeconds: 20,
        retryPolicy: 'FIXED_3_RETRIES',
        inputSchema: '{orderId, complaintType}',
        outputSchema: '{eligibility, actionPlan}',
      },
    },
  },
];

const ticketMcpVersions: ResourceVersion[] = [
  {
    id: 'resource-version-ticket-v1',
    resourceId: 'resource-mcp-ticket',
    version: '1.0.0',
    status: 'PUBLISHED',
    summary: '工单系统集成版',
    configDigest: 'digest-ticket-v1',
    createdAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    configuration: {
      type: 'MCP',
      mcp: {
        serverName: 'ticketing-server',
        transport: 'STREAMABLE_HTTP',
        connectionUri: 'https://mcp-gateway.internal/ticketing',
        namespace: 'support.ticket',
        authType: 'API_KEY',
        heartbeatSeconds: 30,
        exposedTools: ['create_ticket', 'sync_ticket', 'append_comment'],
      },
    },
  },
];

const llmModelVersions: ResourceVersion[] = [
  {
    id: 'resource-version-llm-openai-v1',
    resourceId: 'resource-llm-openai',
    version: '1.0.0',
    status: 'PUBLISHED',
    summary: 'OpenAI 主模型基线版',
    configDigest: 'digest-llm-openai-v1',
    createdAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    configuration: {
      type: 'LLM_MODEL',
      llmModel: {
        providerType: 'OPENAI',
        modelId: 'gpt-4.1-mini',
        baseUrl: 'https://api.openai.com/v1',
        apiKeyEnvVar: 'OPENAI_API_KEY',
        organization: 'lynxus-demo',
        project: 'support-project',
        region: 'global',
        temperature: 0.2,
        maxTokens: 1200,
      },
    },
  },
];

const compatibleLlmModelVersions: ResourceVersion[] = [
  {
    id: 'resource-version-llm-compatible-v1',
    resourceId: 'resource-llm-compatible',
    version: '1.0.0',
    status: 'PUBLISHED',
    summary: '自定义兼容模型基线版',
    configDigest: 'digest-llm-compatible-v1',
    createdAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    configuration: {
      type: 'LLM_MODEL',
      llmModel: {
        providerType: 'OPENAI_COMPATIBLE',
        modelId: 'custom-compatible-model',
        baseUrl: 'http://localhost:11434/v1',
        apiKeyEnvVar: 'OPENAI_COMPATIBLE_API_KEY',
        organization: 'compatible-lab',
        project: 'self-hosted',
        region: 'local',
        temperature: 0.2,
        maxTokens: 1200,
      },
    },
  },
];

const promptSupportVersions: ResourceVersion[] = [
  {
    id: 'resource-version-prompt-support-v1',
    resourceId: 'resource-prompt-support',
    version: '1.0.0',
    status: 'PUBLISHED',
    summary: '问答升级默认 Prompt',
    configDigest: 'digest-prompt-support-v1',
    createdAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    configuration: {
      type: 'PROMPT_TEMPLATE',
      promptTemplate: {
        templateType: 'CHAT',
        systemPrompt: '你是企业客服问答与升级助手。',
        userPromptTemplate: '用户问题：{{question}}\n召回知识：{{knowledge_context}}',
        responseFormat: 'markdown',
      },
    },
  },
];

const resources: Resource[] = [
  {
    id: 'resource-kb-support',
    domainId: 'domain-support',
    name: '客服知识库',
    type: 'KNOWLEDGE_BASE',
    shareScope: 'DOMAIN_SHARED',
    ownerType: 'DOMAIN',
    ownerId: 'domain-support',
    summary: '用于常见问题检索的知识库',
    steward: '客服知识运营',
    tags: ['客服', 'FAQ', '知识检索'],
    latestVersion: kbVersions[kbVersions.length - 1],
    effectiveVersion: kbVersions[0],
    versions: kbVersions,
  },
  {
    id: 'resource-skill-answer',
    domainId: 'domain-support',
    name: '答案生成 Skill',
    type: 'SKILL',
    shareScope: 'PRIVATE',
    ownerType: 'ASSISTANT',
    ownerId: 'assistant-knowledge-escalation',
    summary: '根据检索结果生成可发送答案',
    steward: '问答升级助手团队',
    tags: ['回答生成', '文本输出'],
    latestVersion: answerSkillVersions[0],
    effectiveVersion: answerSkillVersions[0],
    versions: answerSkillVersions,
  },
  {
    id: 'resource-skill-refund',
    domainId: 'domain-support',
    name: '退款策略 Skill',
    type: 'SKILL',
    shareScope: 'PRIVATE',
    ownerType: 'ASSISTANT',
    ownerId: 'assistant-after-sales',
    summary: '用于判断退款资格与补偿策略',
    steward: '售后策略团队',
    tags: ['退款', '售后策略'],
    latestVersion: refundSkillVersions[0],
    effectiveVersion: refundSkillVersions[0],
    versions: refundSkillVersions,
  },
  {
    id: 'resource-mcp-ticket',
    domainId: 'domain-support',
    name: '工单系统 MCP',
    type: 'MCP',
    shareScope: 'DOMAIN_SHARED',
    ownerType: 'DOMAIN',
    ownerId: 'domain-support',
    summary: '用于创建工单和同步人工处理结果',
    steward: '客服平台集成',
    tags: ['MCP', '工单', '协同'],
    latestVersion: ticketMcpVersions[0],
    effectiveVersion: ticketMcpVersions[0],
    versions: ticketMcpVersions,
  },
  {
    id: 'resource-llm-openai',
    domainId: 'domain-support',
    name: 'OpenAI 客服主模型',
    type: 'LLM_MODEL',
    shareScope: 'DOMAIN_SHARED',
    ownerType: 'DOMAIN',
    ownerId: 'domain-support',
    summary: '默认客服 LLM 模型资源',
    steward: '平台 AI 工程团队',
    tags: ['LLM', 'OpenAI'],
    latestVersion: llmModelVersions[0],
    effectiveVersion: llmModelVersions[0],
    versions: llmModelVersions,
  },
  {
    id: 'resource-llm-compatible',
    domainId: 'domain-support',
    name: '自定义 OpenAI Compatible 模型',
    type: 'LLM_MODEL',
    shareScope: 'DOMAIN_SHARED',
    ownerType: 'DOMAIN',
    ownerId: 'domain-support',
    summary: '用于接入兼容 OpenAI API 的自定义模型网关或私有化模型服务',
    steward: '平台 AI 工程团队',
    tags: ['LLM', 'OpenAI-Compatible', '自定义'],
    latestVersion: compatibleLlmModelVersions[0],
    effectiveVersion: compatibleLlmModelVersions[0],
    versions: compatibleLlmModelVersions,
  },
  {
    id: 'resource-prompt-support',
    domainId: 'domain-support',
    name: '问答升级 Prompt',
    type: 'PROMPT_TEMPLATE',
    shareScope: 'PRIVATE',
    ownerType: 'ASSISTANT',
    ownerId: 'assistant-knowledge-escalation',
    summary: '问答升级默认 Prompt',
    steward: '问答升级助手团队',
    tags: ['Prompt'],
    latestVersion: promptSupportVersions[0],
    effectiveVersion: promptSupportVersions[0],
    versions: promptSupportVersions,
  },
];

const agents: Agent[] = [
  {
    id: 'agent-router',
    assistantId: 'assistant-knowledge-escalation',
    name: '问题路由智能体',
    role: 'router',
    instructions: '识别问题类型，决定直接回答还是进入升级流程',
    bindings: [
      {
        id: 'binding-kb-router',
        resourceId: 'resource-kb-support',
        resourceVersionId: 'resource-version-kb-v1',
        resourceVersion: '1.0.0',
        consumerType: 'AGENT',
        consumerId: 'agent-router',
        createdAt: new Date().toISOString(),
      },
    ],
    executionPolicy: {
      inheritAssistantDefaults: true,
      modelResourceId: null,
      promptTemplateResourceId: 'resource-prompt-support',
      inlinePrompt: '判断问题类型并决定路由方向',
      ragEnabled: true,
      knowledgeBaseResourceId: 'resource-kb-support',
      memoryWindowSize: 8,
      toolResourceIds: [],
    },
  },
  {
    id: 'agent-responder',
    assistantId: 'assistant-knowledge-escalation',
    name: '回答生成智能体',
    role: 'responder',
    instructions: '根据知识库结果生成结构化答案',
    bindings: [
      {
        id: 'binding-skill-responder',
        resourceId: 'resource-skill-answer',
        resourceVersionId: 'resource-version-answer-v1',
        resourceVersion: '1.0.0',
        consumerType: 'AGENT',
        consumerId: 'agent-responder',
        createdAt: new Date().toISOString(),
      },
    ],
    executionPolicy: {
      inheritAssistantDefaults: true,
      modelResourceId: 'resource-llm-openai',
      promptTemplateResourceId: 'resource-prompt-support',
      inlinePrompt: '基于知识与工具生成最终答复',
      ragEnabled: true,
      knowledgeBaseResourceId: 'resource-kb-support',
      memoryWindowSize: 8,
      toolResourceIds: ['resource-skill-answer'],
    },
  },
  {
    id: 'agent-refund-policy',
    assistantId: 'assistant-after-sales',
    name: '退款策略智能体',
    role: 'policy',
    instructions: '根据售后规则判断退款、补偿和处理路径',
    bindings: [
      {
        id: 'binding-skill-refund',
        resourceId: 'resource-skill-refund',
        resourceVersionId: 'resource-version-refund-v1',
        resourceVersion: '1.0.0',
        consumerType: 'AGENT',
        consumerId: 'agent-refund-policy',
        createdAt: new Date().toISOString(),
      },
    ],
    executionPolicy: {
      inheritAssistantDefaults: true,
      modelResourceId: 'resource-llm-openai',
      promptTemplateResourceId: 'resource-prompt-support',
      inlinePrompt: '根据售后规则判断处理路径',
      ragEnabled: true,
      knowledgeBaseResourceId: 'resource-kb-support',
      memoryWindowSize: 8,
      toolResourceIds: ['resource-skill-refund'],
    },
  },
  {
    id: 'agent-human-coordinator',
    assistantId: 'assistant-human-coordination',
    name: '人工协同智能体',
    role: 'handoff',
    instructions: '负责创建工单并同步人工处理结果',
    bindings: [
      {
        id: 'binding-mcp-ticket',
        resourceId: 'resource-mcp-ticket',
        resourceVersionId: 'resource-version-ticket-v1',
        resourceVersion: '1.0.0',
        consumerType: 'AGENT',
        consumerId: 'agent-human-coordinator',
        createdAt: new Date().toISOString(),
      },
    ],
    executionPolicy: {
      inheritAssistantDefaults: true,
      modelResourceId: 'resource-llm-openai',
      promptTemplateResourceId: 'resource-prompt-support',
      inlinePrompt: '总结上下文并创建协同工单',
      ragEnabled: false,
      knowledgeBaseResourceId: null,
      memoryWindowSize: 12,
      toolResourceIds: ['resource-mcp-ticket'],
    },
  },
];

const assistants: Assistant[] = [
  {
    id: 'assistant-knowledge-escalation',
    scenarioId: 'scenario-knowledge-escalation',
    name: '问答升级助手',
    description: '负责知识检索、答案生成和升级判定',
    version: { version: '0.1.0', status: 'PUBLISHED', updatedAt: new Date().toISOString() },
    agents,
    currentRelease: {
      id: 'assistant-release-knowledge-v1',
      assistantId: 'assistant-knowledge-escalation',
      releaseVersion: '0.1.0',
      status: 'PUBLISHED',
      createdAt: new Date().toISOString(),
      publishedAt: new Date().toISOString(),
      resources: [
        {
          resourceId: 'resource-kb-support',
          resourceName: '客服知识库',
          resourceType: 'KNOWLEDGE_BASE',
          resourceVersionId: 'resource-version-kb-v1',
          resourceVersion: '1.0.0',
          boundAgents: ['问题路由智能体'],
        },
        {
          resourceId: 'resource-skill-answer',
          resourceName: '答案生成 Skill',
          resourceType: 'SKILL',
          resourceVersionId: 'resource-version-answer-v1',
          resourceVersion: '1.0.0',
          boundAgents: ['回答生成智能体'],
        },
      ],
    },
    releases: [
      {
        id: 'assistant-release-knowledge-v1',
        assistantId: 'assistant-knowledge-escalation',
        releaseVersion: '0.1.0',
        status: 'PUBLISHED',
        createdAt: new Date().toISOString(),
        publishedAt: new Date().toISOString(),
        resources: [
          {
            resourceId: 'resource-kb-support',
            resourceName: '客服知识库',
            resourceType: 'KNOWLEDGE_BASE',
            resourceVersionId: 'resource-version-kb-v1',
            resourceVersion: '1.0.0',
            boundAgents: ['问题路由智能体'],
          },
          {
            resourceId: 'resource-skill-answer',
            resourceName: '答案生成 Skill',
            resourceType: 'SKILL',
            resourceVersionId: 'resource-version-answer-v1',
            resourceVersion: '1.0.0',
            boundAgents: ['回答生成智能体'],
          },
        ],
      },
    ],
    modelPolicy: {
      providerResourceId: 'resource-llm-openai',
      promptTemplateResourceId: 'resource-prompt-support',
      temperature: 0.2,
      maxTokens: 1200,
    },
    ragPolicy: {
      enabled: true,
      knowledgeBaseResourceId: 'resource-kb-support',
      topK: 5,
    },
    memoryPolicy: {
      enabled: true,
      windowSize: 8,
    },
  },
  {
    id: 'assistant-after-sales',
    scenarioId: 'scenario-knowledge-escalation',
    name: '售后策略助手',
    description: '负责退款、补偿和售后政策解释',
    version: { version: '0.1.0', status: 'PUBLISHED', updatedAt: new Date().toISOString() },
    agents: [],
    currentRelease: null,
    releases: [],
    modelPolicy: {
      providerResourceId: 'resource-llm-openai',
      promptTemplateResourceId: 'resource-prompt-support',
      temperature: 0.2,
      maxTokens: 1200,
    },
    ragPolicy: {
      enabled: true,
      knowledgeBaseResourceId: 'resource-kb-support',
      topK: 4,
    },
    memoryPolicy: {
      enabled: true,
      windowSize: 8,
    },
  },
  {
    id: 'assistant-human-coordination',
    scenarioId: 'scenario-knowledge-escalation',
    name: '人工协同助手',
    description: '负责人工接管、工单协同和升级闭环',
    version: { version: '0.1.0', status: 'PUBLISHED', updatedAt: new Date().toISOString() },
    agents: [],
    currentRelease: null,
    releases: [],
    modelPolicy: {
      providerResourceId: 'resource-llm-openai',
      promptTemplateResourceId: 'resource-prompt-support',
      temperature: 0.1,
      maxTokens: 1000,
    },
    ragPolicy: {
      enabled: false,
      knowledgeBaseResourceId: 'resource-kb-support',
      topK: 3,
    },
    memoryPolicy: {
      enabled: true,
      windowSize: 12,
    },
  },
];

const resourceBlueprints: ResourceBlueprint[] = [
  {
    type: 'KNOWLEDGE_BASE',
    label: '知识库',
    description: '维护文档来源、索引同步和检索策略，适合问答、检索增强和规则解释场景。',
    maintainedFields: ['数据来源', '同步方式', '检索模式', 'Embedding 模型', '切片策略', '默认召回数', '文档规模'],
    defaultConfiguration: {
      type: 'KNOWLEDGE_BASE',
      knowledgeBase: {
        sourceType: 'OBJECT_STORAGE',
        sourceLocation: 'minio://knowledge/new-resource',
        syncMode: 'MANUAL',
        retrievalMode: 'HYBRID',
        embeddingModel: 'text-embedding-3-large',
        chunkStrategy: 'markdown-512-overlap-80',
        defaultTopK: 5,
        documentCount: 0,
      },
    },
  },
  {
    type: 'SKILL',
    label: 'Skill',
    description: '维护动作能力的调用协议、超时重试和输入输出契约，适合对接业务能力。',
    maintainedFields: ['运行方式', '调用端点', '鉴权方式', '超时设置', '重试策略', '输入 Schema', '输出 Schema'],
    defaultConfiguration: {
      type: 'SKILL',
      skill: {
        runtime: 'HTTP',
        endpoint: 'https://skill-gateway.internal/new-skill',
        method: 'POST',
        authType: 'SERVICE_ACCOUNT',
        timeoutSeconds: 15,
        retryPolicy: 'EXPONENTIAL_BACKOFF',
        inputSchema: '{input}',
        outputSchema: '{output}',
      },
    },
  },
  {
    type: 'LLM_MODEL',
    label: 'LLM 模型',
    description: '维护多供应商模型连接、默认参数和鉴权入口。',
    maintainedFields: ['供应商类型', '模型 ID', 'Base URL', 'API Key 环境变量', 'Organization/Project/Region', 'Temperature', 'Max Tokens'],
    defaultConfiguration: llmModelVersions[0].configuration,
  },
  {
    type: 'PROMPT_TEMPLATE',
    label: 'Prompt 模板',
    description: '维护系统提示、用户模板和输出格式约束。',
    maintainedFields: ['模板类型', 'System Prompt', 'User Prompt Template', '响应格式'],
    defaultConfiguration: promptSupportVersions[0].configuration,
  },
  {
    type: 'MCP',
    label: 'MCP',
    description: '维护外部工具服务的连接方式、命名空间和暴露工具清单，适合连接系统工具。',
    maintainedFields: ['服务名称', '传输协议', '连接地址', '命名空间', '鉴权方式', '心跳设置', '暴露工具'],
    defaultConfiguration: {
      type: 'MCP',
      mcp: {
        serverName: 'new-mcp-server',
        transport: 'STREAMABLE_HTTP',
        connectionUri: 'https://mcp-gateway.internal/new-server',
        namespace: 'default.namespace',
        authType: 'API_KEY',
        heartbeatSeconds: 30,
        exposedTools: ['tool_a', 'tool_b'],
      },
    },
  },
];

const scenarios: Scenario[] = [
  {
    id: 'scenario-knowledge-escalation',
    domainId: 'domain-support',
    name: '知识问答升级处理',
    goal: '回答常见问题，复杂问题自动升级给人工坐席',
    version: { version: '0.1.0', status: 'PUBLISHED', updatedAt: new Date().toISOString() },
    assistants,
  },
];

const domains: BusinessDomain[] = [
  {
    id: 'domain-support',
    name: '智能客服域',
    description: '用于知识问答与升级处理的 MVP 业务域',
    scenarios,
    resources,
  },
];

const tasks: TaskInstance[] = [
  {
    id: 'task-1',
    scenarioId: 'scenario-knowledge-escalation',
    assistantId: 'assistant-knowledge-escalation',
    assistantName: '问答升级助手',
    assistantReleaseVersion: '0.1.0',
    question: '怎么重置密码？',
    requester: '业务用户A',
    status: 'COMPLETED',
    createdAt: new Date().toISOString(),
    workflowInstanceId: 'wf-1',
  },
  {
    id: 'task-2',
    scenarioId: 'scenario-knowledge-escalation',
    assistantId: 'assistant-knowledge-escalation',
    assistantName: '问答升级助手',
    assistantReleaseVersion: '0.1.0',
    question: '这是一个客户投诉，需要人工处理',
    requester: '业务用户B',
    status: 'WAITING_HUMAN',
    createdAt: new Date().toISOString(),
    workflowInstanceId: 'wf-2',
  },
];

const workflows: WorkflowInstance[] = [
  {
    id: 'wf-1',
    taskId: 'task-1',
    assistantId: 'assistant-knowledge-escalation',
    assistantName: '问答升级助手',
    assistantReleaseVersion: '0.1.0',
    status: 'COMPLETED',
    summary: '基于知识库结果的回答已发送。',
    escalationRequired: false,
    mcpSummary: {
      capabilityName: '创建协同工单',
      externalTicketId: 'TICKET-10001',
      status: 'RECORDED',
      recommendedAction: 'AUTO_CLOSE',
      detail: '已记录本次问答结果，无需人工介入。',
    },
    resourceAnchors: ['客服知识库@1.0.0', '答案生成 Skill@1.0.0'],
    nodes: [
      { id: 'n-1', workflowInstanceId: 'wf-1', nodeKey: 'question-received', nodeName: '问题接收', status: 'COMPLETED', detail: '收到问题', updatedAt: new Date().toISOString() },
      { id: 'n-2', workflowInstanceId: 'wf-1', nodeKey: 'knowledge-retrieval', nodeName: '知识检索', status: 'COMPLETED', detail: '召回 3 条知识', updatedAt: new Date().toISOString() },
      { id: 'n-3', workflowInstanceId: 'wf-1', nodeKey: 'answer-generation', nodeName: '回答生成', status: 'COMPLETED', detail: '生成答案成功', updatedAt: new Date().toISOString() },
      { id: 'n-4', workflowInstanceId: 'wf-1', nodeKey: 'mcp-ticketing', nodeName: 'MCP 协同调用', status: 'COMPLETED', detail: '创建协同工单 / TICKET-10001 / 已记录本次问答结果', updatedAt: new Date().toISOString() },
      { id: 'n-5', workflowInstanceId: 'wf-1', nodeKey: 'escalation-decision', nodeName: '升级判定', status: 'COMPLETED', detail: '无需升级', updatedAt: new Date().toISOString() },
    ],
    interventions: [],
  },
  {
    id: 'wf-2',
    taskId: 'task-2',
    assistantId: 'assistant-knowledge-escalation',
    assistantName: '问答升级助手',
    assistantReleaseVersion: '0.1.0',
    status: 'WAITING_HUMAN',
    summary: '命中投诉关键词，等待人工处理。',
    escalationRequired: true,
    mcpSummary: {
      capabilityName: '创建协同工单',
      externalTicketId: 'TICKET-10002',
      status: 'ACCEPTED',
      recommendedAction: 'HUMAN_HANDOFF',
      detail: '已创建人工协同工单，建议人工坐席接管。',
    },
    resourceAnchors: ['客服知识库@1.0.0', '答案生成 Skill@1.0.0'],
    nodes: [
      { id: 'n-6', workflowInstanceId: 'wf-2', nodeKey: 'question-received', nodeName: '问题接收', status: 'COMPLETED', detail: '收到问题', updatedAt: new Date().toISOString() },
      { id: 'n-7', workflowInstanceId: 'wf-2', nodeKey: 'knowledge-retrieval', nodeName: '知识检索', status: 'COMPLETED', detail: '召回 2 条知识', updatedAt: new Date().toISOString() },
      { id: 'n-8', workflowInstanceId: 'wf-2', nodeKey: 'answer-generation', nodeName: '回答生成', status: 'COMPLETED', detail: '生成初步答案', updatedAt: new Date().toISOString() },
      { id: 'n-9', workflowInstanceId: 'wf-2', nodeKey: 'mcp-ticketing', nodeName: 'MCP 协同调用', status: 'COMPLETED', detail: '创建协同工单 / TICKET-10002 / 已创建人工协同工单', updatedAt: new Date().toISOString() },
      { id: 'n-10', workflowInstanceId: 'wf-2', nodeKey: 'escalation-decision', nodeName: '升级判定', status: 'WAITING_HUMAN', detail: '等待人工接管', updatedAt: new Date().toISOString() },
    ],
    interventions: [
      {
        id: 'h-1',
        workflowInstanceId: 'wf-2',
        action: 'WAIT_CONFIRM',
        operator: 'system',
        comment: '等待人工确认',
        createdAt: new Date().toISOString(),
      },
    ],
  },
];

export const mockCatalogSummary: CatalogSummary = {
  domains,
  scenarios,
  assistants,
  agents,
  resources,
  orchestrations: [
    {
      assistantId: 'assistant-knowledge-escalation',
      assistantName: '问答升级助手',
      scenarioId: 'scenario-knowledge-escalation',
      executionMode: 'SEQUENTIAL_GRAPH',
      nodes: [
        {
          nodeId: 'node-agent-router',
          nodeName: '问题路由智能体',
          nodeType: 'AGENT',
          agentId: 'agent-router',
          description: '识别问题类型，决定路由方向',
          resourceIds: ['resource-kb-support'],
        },
        {
          nodeId: 'node-agent-responder',
          nodeName: '回答生成智能体',
          nodeType: 'AGENT',
          agentId: 'agent-responder',
          description: '根据检索结果生成答案',
          resourceIds: ['resource-skill-answer'],
        },
        {
          nodeId: 'node-agent-escalation',
          nodeName: '升级判定智能体',
          nodeType: 'AGENT',
          agentId: 'agent-escalation',
          description: '判断是否需要转人工',
          resourceIds: [],
        },
      ],
      edges: [
        {
          edgeId: 'edge-1',
          fromNodeId: 'node-agent-router',
          toNodeId: 'node-agent-responder',
          condition: '标准问答链路',
          handoffPolicy: 'direct-handoff',
        },
        {
          edgeId: 'edge-2',
          fromNodeId: 'node-agent-responder',
          toNodeId: 'node-agent-escalation',
          condition: '回答生成完成',
          handoffPolicy: 'conditional-handoff',
        },
      ],
    },
  ] satisfies AssistantOrchestration[],
  resourceCenter: {
    totalResources: 2,
    domainSharedResources: 1,
    privateResources: 1,
    usages: [
      {
        resourceId: 'resource-kb-support',
        resourceName: '客服知识库',
        type: 'KNOWLEDGE_BASE',
        shareScope: 'DOMAIN_SHARED',
        ownerLabel: 'DOMAIN:domain-support',
        latestVersion: '1.1.0',
        effectiveVersion: '1.0.0',
        boundAgents: ['问题路由智能体'],
        boundAssistants: ['问答升级助手'],
        bindingAnchors: ['问题路由智能体 -> 1.0.0'],
      },
      {
        resourceId: 'resource-skill-answer',
        resourceName: '答案生成 Skill',
        type: 'SKILL',
        shareScope: 'PRIVATE',
        ownerLabel: 'ASSISTANT:assistant-knowledge-escalation',
        latestVersion: '1.0.0',
        effectiveVersion: '1.0.0',
        boundAgents: ['回答生成智能体'],
        boundAssistants: ['问答升级助手'],
        bindingAnchors: ['回答生成智能体 -> 1.0.0'],
      },
    ],
  } satisfies ResourceCenter,
  resourceBlueprints,
};

export const mockTasks = tasks;
export const mockWorkflows = workflows;
export const mockSession = session;
